apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: cart-service-config
spec:
  features:
    - name: proxy.grpc
      enabled: true
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "localhost:4318"
      isSecure: false
      protocol: http
